@urlServer = http://localhost:4000

### GET Healthcheck
GET {{urlServer}}

# ------------------------------------
# Events Routes
# ------------------------------------
### GET - All available Events
GET {{urlServer}}/events


### GET - Find by id
GET {{urlServer}}/events/id/0f612268-9065-4ad2-ab5f-741dbe19dfd1


### GET - Find by Name
GET {{urlServer}}/events/name/2026


### GET - Find by Type
GET {{urlServer}}/events/type/TEATRO

### POST - Create new Event
POST {{urlServer}}/events
Content-Type: application/json

{
    "organizerId": "3353c485-46ba-483b-9d74-379940192044",
    "name": "Awesome Drama",
    "description": "Awesome Drama Description...",
    "type": "TEATRO",
    "allotedTickets": "50",
    "eventDate": "2026-02-01T18:00:00",
    "expectedDuration": "2026-02-01T23:00:00",
    "startingSales": "2026-01-05T00:00:01",
    "endingSales": "2026-01-31T23:59:59",
    "price": "45"
}


### POST - Create new Event
POST {{urlServer}}/events
Content-Type: application/json

{
    "organizerId": "3353c485-46ba-483b-9d74-379940192044",
    "name": "Awesome Festival 2026",
    "description": "Awesome Festival 2026 Description...",
    "type": "SHOW",
    "allotedTickets": "200",
    "eventDate": "2026-02-01T18:00:00",
    "expectedDuration": "2026-02-01T23:00:00",
    "startingSales": "2026-01-05T00:00:01",
    "endingSales": "2026-01-31T23:59:59",
    "price": "400"
}

### PATCH - Update Event
PATCH {{urlServer}}/events/id/3f35449c-6954-47eb-a4da-084d3cf35dca
Content-Type: application/json

{
    "organizerId": "3353c485-46ba-483b-9d74-379940192044",
    "name": "Awesome Festival 2026 - Updated via PATCH!",
    "description": "Awesome Festival 2026 Description...",
    "type": "SHOW",
    "allotedTickets": "500",
    "eventDate": "2026-02-01T18:00:00",
    "expectedDuration": "2026-02-01T23:00:00",
    "startingSales": "2026-01-05T00:00:01",
    "endingSales": "2026-01-31T23:59:59",
    "price": "400"
}


### PATCH - Update Event
PATCH {{urlServer}}/events/id/a9cce6c8-56a1-4a38-a46b-6d144d26f2ad
Content-Type: application/json

{
    "type": "TEATRO"
}

### Delete - Delete Event
DELETE {{urlServer}}/events
Content-Type: application/json

{
    "eventId": "c117cc96-a973-45a2-99cf-33d4e21efc1a",
    "organizerId": "3353c485-46ba-483b-9d74-379940192044"
}


# ------------------------------------
# Sales Routes
# ------------------------------------
### POST - Request a new Sale
POST {{urlServer}}/sales
Content-Type: application/json

{
    "eventId": "0f612268-9065-4ad2-ab5f-741dbe19dfd1",
    "userId": "3353c485-46ba-483b-9d74-379940192045"
}

### POST - Request a new Sale invalid
POST {{urlServer}}/sales
Content-Type: application/json

{
    "eventId": "0f612268-9065-4ad2-ab5f-741dbe19dfd2",
    "userId": "3353c485-46ba-483b-9d74-379940192045"
}


### GET - All Sales
GET {{urlServer}}/sales


### GET - getById
GET {{urlServer}}/sales/id/ba50c16a-84bb-4131-ace6-f7c1cd0acb76


### GET - Event Sales
GET {{urlServer}}/sales/event/0f612268-9065-4ad2-ab5f-741dbe19dfd1


### GET - User Sales
GET {{urlServer}}/sales/user/3353c485-46ba-483b-9d74-379940192045

# ----------------------
# Sale Status Actions
# -----------------------
### POST - process Payment
POST {{urlServer}}/sales/process-payment
Content-Type: application/json

{    
    "userId": "3353c485-46ba-483b-9d74-379940192045",
    "saleId": "f56d13e6-decd-4926-bb8d-0e18ec1d0878"
}

### POST - Cancel a Paid Sale: Status changes to REFUNDED
POST {{urlServer}}/sales/cancel
Content-Type: application/json

{    
    "userId": "3353c485-46ba-483b-9d74-379940192045",
    "saleId": "f56d13e6-decd-4926-bb8d-0e18ec1d0878"
}




### POST - Cancel a Open Sale: Status changes to CANCELLED
POST {{urlServer}}/sales/cancel
Content-Type: application/json

{    
    "userId": "3353c485-46ba-483b-9d74-379940192045",
    "saleId": "33b2716f-b5a4-450b-9d99-1889a0b80beb"
}



### GET - getById
GET {{urlServer}}/sales/id/ad9043c8-4863-4a57-870d-5209291e4a49


# ------------------------------------
# Users Client: Just testing OpenFeignClient
# ------------------------------------
### GET - All users via Users Client 
GET {{urlServer}}/clients/users


### GET - User by id via Users Client 
GET {{urlServer}}/clients/users/id/3353c485-46ba-483b-9d74-379940192045
