spring.application.name=gateway

server.port=8080

# -------------
# Eureka Client
# -------------

# Discover server - list
eureka.client.service-url.defaultZone=${NAMESERVER_URL}

# Frontend
gateway.webapp.uri=${WEBAPP_URL}

# Gateway Token
gateway.frontend.token=${GATEWAY_WEBAPP_TOKEN}


# logging.level.org.springframework.cloud.gateway=TRACE
# logging.level.org.springframework.http.server.reactive=DEBUG
# logging.level.org.springframework.cloud.loadbalancer=DEBUG
