#!/bin/bash
set -e

echo "Creating database and user for $DB_NOTIFICATIONS"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER "$DB_NOTIFICATIONS_OWNER" WITH PASSWORD '$DB_NOTIFICATIONS_PASSWORD';
  CREATE DATABASE "$DB_NOTIFICATIONS";
  ALTER DATABASE "$DB_NOTIFICATIONS" OWNER TO "$DB_NOTIFICATIONS_OWNER";
EOSQL
